
metric: "accuracy"
eval_device: "cpu"
max_length: 512
training_arguments:
  output_dir: "fine-tuning-output"
  per_device_train_batch_size: 10
  per_device_eval_batch_size: 10
  num_train_epochs: 10
  learning_rate: 0.0005